# Generated by Django 5.2.3 on 2025-07-02 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_id', models.CharField(db_index=True, help_text='QR Code / Image ID', max_length=100)),
                ('capture_datetime', models.DateTimeField(auto_now_add=True, help_text='Date and time of image capture')),
                ('original_image_ok', models.CharField(blank=True, help_text='Path to original image in OK folder', max_length=500)),
                ('original_image_ng', models.CharField(blank=True, help_text='Path to original image in NG folder', max_length=500)),
                ('annotated_image_ok', models.CharField(blank=True, help_text='Path to annotated image in OK folder', max_length=500)),
                ('annotated_image_ng', models.CharField(blank=True, help_text='Path to annotated image in NG folder', max_length=500)),
                ('nuts_present', models.IntegerField(default=0, help_text='Number of nuts detected as present')),
                ('nuts_absent', models.IntegerField(default=0, help_text='Number of nuts detected as absent')),
                ('total_nuts_expected', models.IntegerField(default=4, help_text='Total nuts expected')),
                ('test_status', models.CharField(choices=[('OK', 'OK - All nuts present (PASS)'), ('NG', 'NG - Some nuts missing (FAIL)')], help_text='OK = Pass (all 4 nuts), NG = Fail (missing nuts)', max_length=2)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('confidence_scores', models.TextField(blank=True, help_text='JSON array of confidence scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Record',
                'verbose_name_plural': 'Inspection Records',
                'ordering': ['-capture_datetime'],
                'indexes': [models.Index(fields=['image_id'], name='ml_api_insp_image_i_c7c64d_idx'), models.Index(fields=['capture_datetime'], name='ml_api_insp_capture_65821e_idx'), models.Index(fields=['test_status'], name='ml_api_insp_test_st_021336_idx'), models.Index(fields=['user', 'capture_datetime'], name='ml_api_insp_user_id_68df41_idx')],
            },
        ),
    ]
